# Generated by Django 4.1.2 on 2022-10-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JefeEnfermeras',
            fields=[
                ('cedula', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=30)),
            ],
            options={
                'verbose_name': 'jefeEnfermeras',
                'verbose_name_plural': 'jefesEnfermeras',
            },
        ),
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('cedula', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=30)),
                ('jefe', models.ManyToManyField(to='MediPlannerApp.jefeenfermeras')),
            ],
        ),
    ]
