# Generated by Django 4.1.2 on 2022-10-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0003_alter_jefeenfermeras_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermera',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jefeenfermeras',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
