# Generated by Django 4.1.2 on 2022-10-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0004_alter_enfermera_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
    ]
