# Generated by Django 4.1.2 on 2022-10-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0005_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_ingreso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_salida',
            field=models.CharField(max_length=100),
        ),
    ]
