# Generated by Django 4.1.2 on 2022-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0006_alter_turno_options_alter_turno_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_ingreso',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='turno',
            name='ingreso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='turno',
            name='salida',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
