# Generated by Django 4.1.2 on 2022-10-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0007_alter_turno_options_remove_turno_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermera',
            name='turno',
            field=models.ManyToManyField(to='MediPlannerApp.turno'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('habitacion', models.CharField(max_length=10)),
                ('fecha_salida', models.DateTimeField()),
                ('novedades', models.TextField()),
                ('enfermeras', models.ManyToManyField(to='MediPlannerApp.enfermera')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
    ]
