# Generated by Django 4.1.2 on 2022-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0008_enfermera_turno_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cantidad', models.CharField(max_length=10)),
                ('invima', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('via_administración', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
            },
        ),
    ]
