# Generated by Django 4.1.1 on 2022-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0010_seguimiento_alter_enfermera_cedula_medicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='via_administración',
            new_name='via_administracion',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='seguimiento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='paciente',
            field=models.ManyToManyField(to='MediPlannerApp.paciente'),
        ),
    ]
