# Generated by Django 4.1.1 on 2022-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPlannerApp', '0011_rename_via_administración_medicamento_via_administracion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicamento',
            new_name='Medicina',
        ),
        migrations.AlterModelOptions(
            name='medicina',
            options={'verbose_name': 'medicina', 'verbose_name_plural': 'medicinas'},
        ),
        migrations.RenameField(
            model_name='medicacion',
            old_name='medicamento',
            new_name='medicina',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicacion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicina',
            field=models.ManyToManyField(to='MediPlannerApp.medicina'),
        ),
    ]
